version: '3.8'
services:
  devcontainer:
    build:
      context: ../.github/containers/ubuntu-latest
      dockerfile: Dockerfile
    volumes:
      - ..:/codectrl:cached
    command: /bin/sh -c "while sleep 1000; do :; done"
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined