name: Auto Reformat
on: pull_request

jobs:
  rustfmt:
    if: github.event.pull_request.head.repo.full_name == github.repository
    name: cargo fmt
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt
      - name: Run cargo fmt
        run: cargo +nightly fmt -- --unstable-features --error-on-unformatted
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)
      - name: Push changes
        if: steps.git-check.outputs.modified == 'true'
        run: |
          echo "# #${{ github.event.number }} ${SHORT_SHA}" >> .git-blame-ignore-revs
          echo "${GITHUB_SHA}" >> .git-blame-ignore-revs
          echo "" >> .git-blame-ignore-revs

          git config --global user.name 'Samuel Boyden'
          git config --global user.email 'stboyden@users.noreply.github.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git commit -am "Automated reformatting changes"
          git push
